language: java

sudo: required

jdk:
  - oraclejdk8

install: true

notifications:
  email:
    recipients:
      - goriar.cb@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
addons:
  sonarcloud:
    organization: "goriar-github"
    token: $BAT_TOKEN

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
